version: "3.8"

services:
  nginx-rtmp:
    build: ./nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    restart: always

  srt-server:
    build: ./srs
    container_name: srt-server
    ports:
      - "10080:10080/udp"
      - "10081:10081/udp"
      - "10082:10082/udp"
    restart: always
