listen              1990;
max_connections     1000;
srs_log_tank        console;

# Cámara 1
srt_server {
    enabled on;
    listen 10080;
    latency 120;
    payload_size 1316;
    mode listener;
}

# Cámara 2
srt_server {
    enabled on;
    listen 10081;
    latency 120;
    payload_size 1316;
    mode listener;
}

# Cámara 3
srt_server {
    enabled on;
    listen 10082;
    latency 120;
    payload_size 1316;
    mode listener;
}
