listen              1990;
max_connections     1000;
srs_log_tank        console;

# =========================
# PUERTOS SRT CÁMARAS
# =========================

srt_server {
    enabled on;
    listen 10080;
    latency 200;
}

srt_server {
    enabled on;
    listen 10081;
    latency 200;
}

srt_server {
    enabled on;
    listen 10082;
    latency 200;
}
