worker_processes 1;
events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/srs/ {
            set $srs_backend http://srs:1985;
            proxy_pass $srs_backend/api/;
            proxy_set_header Host $host;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
